name: nyxx_pagination
description: Pagination utility for nyxx library
version: 1.0.1
issue_tracker: https://github.com/nyxx-discord/nyxx_pagination/issues
repository: https://github.com/nyxx-discord/nyxx_pagination
documentation: https://nyxx.l7ssha.xyz/nyxx_pagination

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  nyxx: ^2.0.0
  nyxx_interactions: ^2.0.0
  random_string: ^2.3.1
