name: nyxx_pagination
description: A starting point for Dart libraries or applications.
version: 1.0.0-dev.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  nyxx: ^2.0.0-rc.12
  nyxx_interactions: ^2.0.0-rc.19
  random_string: ^2.3.1

dev_dependencies:
  test: ^1.16.0
