name: unit tests

on:
  push:
    branches-ignore:
      - main

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: dart-lang/setup-dart@v1

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

  format:
    name: Format
    runs-on: ubuntu-latest
    env:
      TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pub_cache
          key: ${{ runner.os }}

      - name: Setup Dart Action
        uses: dart-lang/setup-dart@v1

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed -l 160 ./lib
